### ISSUE TITLE
For the sake of God

### ISSUE THREAD

**Issue by stabldev** [daaniissh/X#1]
Yo, nice project.
Just dont ever put `.env` variables public.
https://github.com/daaniissh/X/blob/c2af4a413e5e7ea354fa25321f775fa33109ddff/.env

you needed to `git rm -r --cached .` after this commit: https://github.com/daaniissh/X/commit/9822d13843eaed926b2dd308d4346e5a9cd5bb7e

**Comment by daaniissh** [comment]
Hey, thanks for the heads up! I totally missed that. I’ve removed the file 😊

**Comment by daaniissh** [comment]
Hey, thanks for the heads up! I totally missed that. I’ve removed the file 😊
