### ISSUE TITLE
Reduce `fetch` calls

### ISSUE THREAD

**Issue by stabldev** [daaniissh/X#2]
you can add `required` property to input fields to make sure users cant send login request without required credentials.
thus reduce api calls and improve UX.

alternatively: can use `zod` validation on api call and render error fields accordingly.

https://github.com/daaniissh/X/blob/243a011b587805364667e9d4f0ccd33ce675b8ab/client/src/pages/auth/login/Login.jsx#L64-L71

**Comment by daaniissh** [comment]
Hey, thanks , Adding the required property to input fields is a great idea for improving UX and reducing unnecessary API calls. I hadn't thought of using Zod for validation on the API side either, but that sounds super useful. Really appreciate the help!
